version: "2"
services:
  web:
    build: 5.6/apache
    ports:
      - 80:80
    volumes_from:
      - appdata
    environment:
      - HTTPS_METHOD=noredirect
      - ENABLE_SENDMAIL=true
    links:
      - db

  cli:
    build: 5.6/cli
    working_dir: /var/www/html
    command: /bin/true
    volumes_from:
      - appdata
    links:
      - db

  db:
    image: mysql:5.7
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_USER=homestead
      - MYSQL_PASSWORD=secret
      - MYSQL_DATABASE=magento

  appdata:
    image: tianon/true
    volumes:
      - ./magento:/var/www/html
